/* tslint:disable */
/* eslint-disable */
/*
ElevenLabs API Documentation

This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/


export * from './api/pronunciation-dictionary-api';
export * from './api/audio-native-api';
export * from './api/dubbing-api';
export * from './api/models-api';
export * from './api/projects-api';
export * from './api/redirect-api';
export * from './api/samples-api';
export * from './api/speech-history-api';
export * from './api/speech-to-speech-api';
export * from './api/text-to-speech-api';
export * from './api/user-api';
export * from './api/voice-generation-api';
export * from './api/voices-api';
export * from './api/workspace-api';

