/*
ElevenLabs API Documentation

This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BodyDownloadHistoryItemsV1HistoryDownloadPost
 */
export interface BodyDownloadHistoryItemsV1HistoryDownloadPost {
    /**
     * A list of history items to download, you can get IDs of history items and other metadata using the GET https://api.elevenlabs.io/v1/history endpoint.
     * @type {Array<string>}
     * @memberof BodyDownloadHistoryItemsV1HistoryDownloadPost
     */
    'history_item_ids': Array<string>;
}

