/*
ElevenLabs API Documentation

This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost
 */
export interface BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost {
    /**
     * Name to use for the created voice.
     * @type {string}
     * @memberof BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost
     */
    'voice_name': string;
    /**
     * Description to use for the created voice.
     * @type {string}
     * @memberof BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost
     */
    'voice_description': string;
    /**
     * The generated_voice_id to create, call POST /v1/voice-generation/generate-voice and fetch the generated_voice_id from the response header if don\'t have one yet.
     * @type {string}
     * @memberof BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost
     */
    'generated_voice_id': string;
    /**
     * Optional, metadata to add to the created voice. Defaults to None.
     * @type {{ [key: string]: string; }}
     * @memberof BodyCreateAPreviouslyGeneratedVoiceV1VoiceGenerationCreateVoicePost
     */
    'labels'?: { [key: string]: string; };
}

