/*
ElevenLabs API Documentation

This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BodyGenerateARandomVoiceV1VoiceGenerationGenerateVoicePost
 */
export interface BodyGenerateARandomVoiceV1VoiceGenerationGenerateVoicePost {
    /**
     * Category code corresponding to the gender of the generated voice. Possible values: female, male.
     * @type {string}
     * @memberof BodyGenerateARandomVoiceV1VoiceGenerationGenerateVoicePost
     */
    'gender': BodyGenerateARandomVoiceV1VoiceGenerationGenerateVoicePostGenderEnum;
    /**
     * Category code corresponding to the accent of the generated voice. Possible values: american, british, african, australian, indian.
     * @type {string}
     * @memberof BodyGenerateARandomVoiceV1VoiceGenerationGenerateVoicePost
     */
    'accent': string;
    /**
     * Category code corresponding to the age of the generated voice. Possible values: young, middle_aged, old.
     * @type {string}
     * @memberof BodyGenerateARandomVoiceV1VoiceGenerationGenerateVoicePost
     */
    'age': BodyGenerateARandomVoiceV1VoiceGenerationGenerateVoicePostAgeEnum;
    /**
     * The strength of the accent of the generated voice. Has to be between 0.3 and 2.0.
     * @type {number}
     * @memberof BodyGenerateARandomVoiceV1VoiceGenerationGenerateVoicePost
     */
    'accent_strength': number;
    /**
     * Text to generate, text length has to be between 100 and 1000.
     * @type {string}
     * @memberof BodyGenerateARandomVoiceV1VoiceGenerationGenerateVoicePost
     */
    'text': string;
}

type BodyGenerateARandomVoiceV1VoiceGenerationGenerateVoicePostGenderEnum = 'female' | 'male'
type BodyGenerateARandomVoiceV1VoiceGenerationGenerateVoicePostAgeEnum = 'young' | 'middle_aged' | 'old'


