/*
ElevenLabs API Documentation

This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BodyCreatesAudioNativeEnabledProjectV1AudioNativePost
 */
export interface BodyCreatesAudioNativeEnabledProjectV1AudioNativePost {
    /**
     * Title used in the player and inserted at the top of the uploaded article. If not provided, the default title set in the Player settings is used.
     * @type {string}
     * @memberof BodyCreatesAudioNativeEnabledProjectV1AudioNativePost
     */
    'title'?: string;
    /**
     * Project name.
     * @type {string}
     * @memberof BodyCreatesAudioNativeEnabledProjectV1AudioNativePost
     */
    'name': string;
    /**
     * Image URL used in the player. If not provided, default image set in the Player settings is used.
     * @type {string}
     * @memberof BodyCreatesAudioNativeEnabledProjectV1AudioNativePost
     */
    'image'?: string;
    /**
     * Author used in the player and inserted at the start of the uploaded article. If not provided, the default author set in the Player settings is used.
     * @type {string}
     * @memberof BodyCreatesAudioNativeEnabledProjectV1AudioNativePost
     */
    'author'?: string;
    /**
     * Whether to use small player or not. If not provided, default value set in the Player settings is used.
     * @type {boolean}
     * @memberof BodyCreatesAudioNativeEnabledProjectV1AudioNativePost
     */
    'small'?: boolean;
    /**
     * Text color used in the player. If not provided, default text color set in the Player settings is used.
     * @type {string}
     * @memberof BodyCreatesAudioNativeEnabledProjectV1AudioNativePost
     */
    'text_color'?: string;
    /**
     * Background color used in the player. If not provided, default background color set in the Player settings is used.
     * @type {string}
     * @memberof BodyCreatesAudioNativeEnabledProjectV1AudioNativePost
     */
    'background_color'?: string;
    /**
     * Specifies for how many minutes to persist the session across page reloads. If not provided, default sessionization set in the Player settings is used.
     * @type {number}
     * @memberof BodyCreatesAudioNativeEnabledProjectV1AudioNativePost
     */
    'sessionization'?: number;
    /**
     * Voice ID used to voice the content. If not provided, default voice ID set in the Player settings is used.
     * @type {string}
     * @memberof BodyCreatesAudioNativeEnabledProjectV1AudioNativePost
     */
    'voice_id'?: string;
    /**
     * TTS Model ID used in the player. If not provided, default model ID set in the Player settings is used.
     * @type {string}
     * @memberof BodyCreatesAudioNativeEnabledProjectV1AudioNativePost
     */
    'model_id'?: string;
    /**
     * Either txt or HTML input file containing the article content. HTML should be formatted as follows \'&lt;html&gt;&lt;body&gt;&lt;div&gt;&lt;p&gt;Your content&lt;/p&gt;&lt;h5&gt;More of your content&lt;/h5&gt;&lt;p&gt;Some more of your content&lt;/p&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;\'
     * @type {Uint8Array | File | buffer.File}
     * @memberof BodyCreatesAudioNativeEnabledProjectV1AudioNativePost
     */
    'file': Uint8Array | File | buffer.File;
    /**
     * Whether to auto convert the project to audio or not.
     * @type {boolean}
     * @memberof BodyCreatesAudioNativeEnabledProjectV1AudioNativePost
     */
    'auto_convert'?: boolean;
}

