/*
ElevenLabs API Documentation

This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BodyEditVoiceV1VoicesVoiceIdEditPost
 */
export interface BodyEditVoiceV1VoicesVoiceIdEditPost {
    /**
     * How would you describe the voice?
     * @type {string}
     * @memberof BodyEditVoiceV1VoicesVoiceIdEditPost
     */
    'description'?: string;
    /**
     * The name that identifies this voice. This will be displayed in the dropdown of the website.
     * @type {string}
     * @memberof BodyEditVoiceV1VoicesVoiceIdEditPost
     */
    'name': string;
    /**
     * Audio files to add to the voice
     * @type {Array<Uint8Array | File | buffer.File>}
     * @memberof BodyEditVoiceV1VoicesVoiceIdEditPost
     */
    'files'?: Array<Uint8Array | File | buffer.File>;
    /**
     * Serialized labels dictionary for the voice.
     * @type {string}
     * @memberof BodyEditVoiceV1VoicesVoiceIdEditPost
     */
    'labels'?: string;
}

