/*
ElevenLabs API Documentation

This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePost
 */
export interface BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePost {
    /**
     * A description of the pronunciation dictionary, used for identification only.
     * @type {string}
     * @memberof BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePost
     */
    'description'?: string;
    /**
     * A lexicon .pls file which we will use to initialize the project with.
     * @type {Uint8Array | File | buffer.File}
     * @memberof BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePost
     */
    'file'?: Uint8Array | File | buffer.File;
    /**
     * The name of the pronunciation dictionary, used for identification only.
     * @type {string}
     * @memberof BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePost
     */
    'name': string;
}

