/*
ElevenLabs API Documentation

This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ChapterStatisticsResponseModel } from './chapter-statistics-response-model';

/**
 * 
 * @export
 * @interface ChapterResponseModel
 */
export interface ChapterResponseModel {
    /**
     * 
     * @type {string}
     * @memberof ChapterResponseModel
     */
    'chapter_id': string;
    /**
     * 
     * @type {string}
     * @memberof ChapterResponseModel
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof ChapterResponseModel
     */
    'last_conversion_date_unix': number;
    /**
     * 
     * @type {number}
     * @memberof ChapterResponseModel
     */
    'conversion_progress': number;
    /**
     * 
     * @type {boolean}
     * @memberof ChapterResponseModel
     */
    'can_be_downloaded': boolean;
    /**
     * 
     * @type {string}
     * @memberof ChapterResponseModel
     */
    'state': ChapterResponseModelStateEnum;
    /**
     * 
     * @type {ChapterStatisticsResponseModel}
     * @memberof ChapterResponseModel
     */
    'statistics': ChapterStatisticsResponseModel;
}

type ChapterResponseModelStateEnum = 'default' | 'converting'


