/*
ElevenLabs API Documentation

This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InvoiceResponseModel } from './invoice-response-model';

/**
 * 
 * @export
 * @interface ExtendedSubscriptionResponseModel
 */
export interface ExtendedSubscriptionResponseModel {
    /**
     * 
     * @type {string}
     * @memberof ExtendedSubscriptionResponseModel
     */
    'tier': string;
    /**
     * 
     * @type {number}
     * @memberof ExtendedSubscriptionResponseModel
     */
    'character_count': number;
    /**
     * 
     * @type {number}
     * @memberof ExtendedSubscriptionResponseModel
     */
    'character_limit': number;
    /**
     * 
     * @type {boolean}
     * @memberof ExtendedSubscriptionResponseModel
     */
    'can_extend_character_limit': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ExtendedSubscriptionResponseModel
     */
    'allowed_to_extend_character_limit': boolean;
    /**
     * 
     * @type {number}
     * @memberof ExtendedSubscriptionResponseModel
     */
    'next_character_count_reset_unix': number;
    /**
     * 
     * @type {number}
     * @memberof ExtendedSubscriptionResponseModel
     */
    'voice_limit': number;
    /**
     * 
     * @type {number}
     * @memberof ExtendedSubscriptionResponseModel
     */
    'max_voice_add_edits': number;
    /**
     * 
     * @type {number}
     * @memberof ExtendedSubscriptionResponseModel
     */
    'voice_add_edit_counter': number;
    /**
     * 
     * @type {number}
     * @memberof ExtendedSubscriptionResponseModel
     */
    'professional_voice_limit': number;
    /**
     * 
     * @type {boolean}
     * @memberof ExtendedSubscriptionResponseModel
     */
    'can_extend_voice_limit': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ExtendedSubscriptionResponseModel
     */
    'can_use_instant_voice_cloning': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ExtendedSubscriptionResponseModel
     */
    'can_use_professional_voice_cloning': boolean;
    /**
     * 
     * @type {string}
     * @memberof ExtendedSubscriptionResponseModel
     */
    'currency': ExtendedSubscriptionResponseModelCurrencyEnum;
    /**
     * 
     * @type {string}
     * @memberof ExtendedSubscriptionResponseModel
     */
    'status': ExtendedSubscriptionResponseModelStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ExtendedSubscriptionResponseModel
     */
    'billing_period': ExtendedSubscriptionResponseModelBillingPeriodEnum;
    /**
     * 
     * @type {InvoiceResponseModel}
     * @memberof ExtendedSubscriptionResponseModel
     */
    'next_invoice': InvoiceResponseModel;
    /**
     * 
     * @type {boolean}
     * @memberof ExtendedSubscriptionResponseModel
     */
    'has_open_invoices': boolean;
}

type ExtendedSubscriptionResponseModelCurrencyEnum = 'usd' | 'eur'
type ExtendedSubscriptionResponseModelStatusEnum = 'trialing' | 'active' | 'incomplete' | 'incomplete_expired' | 'past_due' | 'canceled' | 'unpaid' | 'free'
type ExtendedSubscriptionResponseModelBillingPeriodEnum = 'monthly_period' | 'annual_period'


