/*
ElevenLabs API Documentation

This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ManualVerificationResponseModel } from './manual-verification-response-model';
import { VerificationAttemptResponseModel } from './verification-attempt-response-model';

/**
 * 
 * @export
 * @interface FineTuningResponseModel
 */
export interface FineTuningResponseModel {
    /**
     * 
     * @type {boolean}
     * @memberof FineTuningResponseModel
     */
    'is_allowed_to_fine_tune': boolean;
    /**
     * 
     * @type {string}
     * @memberof FineTuningResponseModel
     */
    'finetuning_state': FineTuningResponseModelFinetuningStateEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof FineTuningResponseModel
     */
    'verification_failures': Array<string>;
    /**
     * 
     * @type {number}
     * @memberof FineTuningResponseModel
     */
    'verification_attempts_count': number;
    /**
     * 
     * @type {boolean}
     * @memberof FineTuningResponseModel
     */
    'manual_verification_requested': boolean;
    /**
     * 
     * @type {string}
     * @memberof FineTuningResponseModel
     */
    'language'?: string;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof FineTuningResponseModel
     */
    'finetuning_progress'?: { [key: string]: number; };
    /**
     * 
     * @type {string}
     * @memberof FineTuningResponseModel
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof FineTuningResponseModel
     */
    'dataset_duration_seconds'?: number;
    /**
     * 
     * @type {Array<VerificationAttemptResponseModel>}
     * @memberof FineTuningResponseModel
     */
    'verification_attempts'?: Array<VerificationAttemptResponseModel>;
    /**
     * 
     * @type {Array<string>}
     * @memberof FineTuningResponseModel
     */
    'slice_ids'?: Array<string>;
    /**
     * 
     * @type {ManualVerificationResponseModel}
     * @memberof FineTuningResponseModel
     */
    'manual_verification'?: ManualVerificationResponseModel;
}

type FineTuningResponseModelFinetuningStateEnum = 'not_started' | 'queued' | 'fine_tuning' | 'fine_tuned' | 'failed' | 'delayed'


