/*
ElevenLabs API Documentation

This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface LibraryVoiceResponseModel
 */
export interface LibraryVoiceResponseModel {
    /**
     * 
     * @type {string}
     * @memberof LibraryVoiceResponseModel
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof LibraryVoiceResponseModel
     */
    'public_owner_id': string;
    /**
     * 
     * @type {string}
     * @memberof LibraryVoiceResponseModel
     */
    'voice_id': string;
    /**
     * 
     * @type {number}
     * @memberof LibraryVoiceResponseModel
     */
    'date_unix': number;
    /**
     * 
     * @type {string}
     * @memberof LibraryVoiceResponseModel
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof LibraryVoiceResponseModel
     */
    'accent': string;
    /**
     * 
     * @type {string}
     * @memberof LibraryVoiceResponseModel
     */
    'gender': string;
    /**
     * 
     * @type {string}
     * @memberof LibraryVoiceResponseModel
     */
    'age': string;
    /**
     * 
     * @type {string}
     * @memberof LibraryVoiceResponseModel
     */
    'descriptive': string;
    /**
     * 
     * @type {string}
     * @memberof LibraryVoiceResponseModel
     */
    'use_case': string;
    /**
     * 
     * @type {string}
     * @memberof LibraryVoiceResponseModel
     */
    'category': string;
    /**
     * 
     * @type {string}
     * @memberof LibraryVoiceResponseModel
     */
    'language': string;
    /**
     * 
     * @type {string}
     * @memberof LibraryVoiceResponseModel
     */
    'preview_url': string;
    /**
     * 
     * @type {number}
     * @memberof LibraryVoiceResponseModel
     */
    'usage_character_count_1y': number;
    /**
     * 
     * @type {number}
     * @memberof LibraryVoiceResponseModel
     */
    'usage_character_count_7d': number;
    /**
     * 
     * @type {number}
     * @memberof LibraryVoiceResponseModel
     */
    'cloned_by_count': number;
    /**
     * 
     * @type {number}
     * @memberof LibraryVoiceResponseModel
     */
    'rate': number;
    /**
     * 
     * @type {boolean}
     * @memberof LibraryVoiceResponseModel
     */
    'free_users_allowed': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LibraryVoiceResponseModel
     */
    'live_moderation_enabled': boolean;
    /**
     * 
     * @type {number}
     * @memberof LibraryVoiceResponseModel
     */
    'notice_period': number;
    /**
     * 
     * @type {string}
     * @memberof LibraryVoiceResponseModel
     */
    'instagram_username': string;
    /**
     * 
     * @type {string}
     * @memberof LibraryVoiceResponseModel
     */
    'twitter_username': string;
    /**
     * 
     * @type {string}
     * @memberof LibraryVoiceResponseModel
     */
    'youtube_username': string;
    /**
     * 
     * @type {string}
     * @memberof LibraryVoiceResponseModel
     */
    'tiktok_username': string;
    /**
     * 
     * @type {boolean}
     * @memberof LibraryVoiceResponseModel
     */
    'featured': boolean;
}

