/*
ElevenLabs API Documentation

This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ManualVerificationFileResponseModel } from './manual-verification-file-response-model';

/**
 * 
 * @export
 * @interface ManualVerificationResponseModel
 */
export interface ManualVerificationResponseModel {
    /**
     * 
     * @type {string}
     * @memberof ManualVerificationResponseModel
     */
    'extra_text': string;
    /**
     * 
     * @type {number}
     * @memberof ManualVerificationResponseModel
     */
    'request_time_unix': number;
    /**
     * 
     * @type {Array<ManualVerificationFileResponseModel>}
     * @memberof ManualVerificationResponseModel
     */
    'files': Array<ManualVerificationFileResponseModel>;
}

