/*
ElevenLabs API Documentation

This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ChapterResponseModel } from './chapter-response-model';

/**
 * 
 * @export
 * @interface ProjectExtendedResponseModel
 */
export interface ProjectExtendedResponseModel {
    /**
     * 
     * @type {string}
     * @memberof ProjectExtendedResponseModel
     */
    'project_id': string;
    /**
     * 
     * @type {string}
     * @memberof ProjectExtendedResponseModel
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof ProjectExtendedResponseModel
     */
    'create_date_unix': number;
    /**
     * 
     * @type {string}
     * @memberof ProjectExtendedResponseModel
     */
    'default_title_voice_id': string;
    /**
     * 
     * @type {string}
     * @memberof ProjectExtendedResponseModel
     */
    'default_paragraph_voice_id': string;
    /**
     * 
     * @type {string}
     * @memberof ProjectExtendedResponseModel
     */
    'default_model_id': string;
    /**
     * 
     * @type {number}
     * @memberof ProjectExtendedResponseModel
     */
    'last_conversion_date_unix': number;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectExtendedResponseModel
     */
    'can_be_downloaded': boolean;
    /**
     * 
     * @type {string}
     * @memberof ProjectExtendedResponseModel
     */
    'state': ProjectExtendedResponseModelStateEnum;
    /**
     * 
     * @type {Array<ChapterResponseModel>}
     * @memberof ProjectExtendedResponseModel
     */
    'chapters': Array<ChapterResponseModel>;
}

type ProjectExtendedResponseModelStateEnum = 'default' | 'converting' | 'in_queue'


