/*
ElevenLabs API Documentation

This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProjectResponseModel
 */
export interface ProjectResponseModel {
    /**
     * 
     * @type {string}
     * @memberof ProjectResponseModel
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponseModel
     */
    'project_id': string;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponseModel
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof ProjectResponseModel
     */
    'create_date_unix': number;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponseModel
     */
    'default_title_voice_id': string;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponseModel
     */
    'default_paragraph_voice_id': string;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponseModel
     */
    'default_model_id': string;
    /**
     * 
     * @type {number}
     * @memberof ProjectResponseModel
     */
    'last_conversion_date_unix': number;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectResponseModel
     */
    'can_be_downloaded': boolean;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponseModel
     */
    'author': string;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponseModel
     */
    'isbn_number': string;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectResponseModel
     */
    'volume_normalization': boolean;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponseModel
     */
    'state': ProjectResponseModelStateEnum;
}

type ProjectResponseModelStateEnum = 'default' | 'converting'


