/*
ElevenLabs API Documentation

This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeedbackResponseModel } from './feedback-response-model';

/**
 * 
 * @export
 * @interface SpeechHistoryItemResponseModel
 */
export interface SpeechHistoryItemResponseModel {
    /**
     * 
     * @type {string}
     * @memberof SpeechHistoryItemResponseModel
     */
    'history_item_id': string;
    /**
     * 
     * @type {string}
     * @memberof SpeechHistoryItemResponseModel
     */
    'request_id': string;
    /**
     * 
     * @type {string}
     * @memberof SpeechHistoryItemResponseModel
     */
    'voice_id': string;
    /**
     * 
     * @type {string}
     * @memberof SpeechHistoryItemResponseModel
     */
    'model_id': string;
    /**
     * 
     * @type {string}
     * @memberof SpeechHistoryItemResponseModel
     */
    'voice_name': string;
    /**
     * 
     * @type {string}
     * @memberof SpeechHistoryItemResponseModel
     */
    'voice_category': SpeechHistoryItemResponseModelVoiceCategoryEnum;
    /**
     * 
     * @type {string}
     * @memberof SpeechHistoryItemResponseModel
     */
    'text': string;
    /**
     * 
     * @type {number}
     * @memberof SpeechHistoryItemResponseModel
     */
    'date_unix': number;
    /**
     * 
     * @type {number}
     * @memberof SpeechHistoryItemResponseModel
     */
    'character_count_change_from': number;
    /**
     * 
     * @type {number}
     * @memberof SpeechHistoryItemResponseModel
     */
    'character_count_change_to': number;
    /**
     * 
     * @type {string}
     * @memberof SpeechHistoryItemResponseModel
     */
    'content_type': string;
    /**
     * 
     * @type {string}
     * @memberof SpeechHistoryItemResponseModel
     */
    'state': SpeechHistoryItemResponseModelStateEnum;
    /**
     * 
     * @type {object}
     * @memberof SpeechHistoryItemResponseModel
     */
    'settings': object;
    /**
     * 
     * @type {FeedbackResponseModel}
     * @memberof SpeechHistoryItemResponseModel
     */
    'feedback': FeedbackResponseModel;
    /**
     * 
     * @type {string}
     * @memberof SpeechHistoryItemResponseModel
     */
    'share_link_id': string;
    /**
     * 
     * @type {string}
     * @memberof SpeechHistoryItemResponseModel
     */
    'source': SpeechHistoryItemResponseModelSourceEnum;
}

type SpeechHistoryItemResponseModelVoiceCategoryEnum = 'premade' | 'cloned' | 'generated' | 'professional'
type SpeechHistoryItemResponseModelStateEnum = 'created' | 'deleted' | 'processing'
type SpeechHistoryItemResponseModelSourceEnum = 'TTS' | 'STS'


