/*
ElevenLabs API Documentation

This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VerificationAttemptResponseModel } from './verification-attempt-response-model';

/**
 * 
 * @export
 * @interface VoiceVerificationResponseModel
 */
export interface VoiceVerificationResponseModel {
    /**
     * 
     * @type {boolean}
     * @memberof VoiceVerificationResponseModel
     */
    'requires_verification': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof VoiceVerificationResponseModel
     */
    'is_verified': boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof VoiceVerificationResponseModel
     */
    'verification_failures': Array<string>;
    /**
     * 
     * @type {number}
     * @memberof VoiceVerificationResponseModel
     */
    'verification_attempts_count': number;
    /**
     * 
     * @type {string}
     * @memberof VoiceVerificationResponseModel
     */
    'language'?: string;
    /**
     * 
     * @type {Array<VerificationAttemptResponseModel>}
     * @memberof VoiceVerificationResponseModel
     */
    'verification_attempts'?: Array<VerificationAttemptResponseModel>;
}

