/*
ElevenLabs API Documentation

This is the documentation for the ElevenLabs API. You can use this API to use our service programmatically, this is done by using your xi-api-key. <br/> You can view your xi-api-key using the 'Profile' tab on https://elevenlabs.io. Our API is experimental so all endpoints are subject to change.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VoiceSharingResponseModel
 */
export interface VoiceSharingResponseModel {
    /**
     * 
     * @type {string}
     * @memberof VoiceSharingResponseModel
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof VoiceSharingResponseModel
     */
    'status': VoiceSharingResponseModelStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof VoiceSharingResponseModel
     */
    'history_item_sample_id': string;
    /**
     * 
     * @type {number}
     * @memberof VoiceSharingResponseModel
     */
    'date_unix': number;
    /**
     * 
     * @type {Array<string>}
     * @memberof VoiceSharingResponseModel
     */
    'whitelisted_emails': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof VoiceSharingResponseModel
     */
    'public_owner_id': string;
    /**
     * 
     * @type {string}
     * @memberof VoiceSharingResponseModel
     */
    'original_voice_id': string;
    /**
     * 
     * @type {boolean}
     * @memberof VoiceSharingResponseModel
     */
    'financial_rewards_enabled': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof VoiceSharingResponseModel
     */
    'free_users_allowed': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof VoiceSharingResponseModel
     */
    'live_moderation_enabled': boolean;
    /**
     * 
     * @type {number}
     * @memberof VoiceSharingResponseModel
     */
    'rate': number;
    /**
     * 
     * @type {number}
     * @memberof VoiceSharingResponseModel
     */
    'notice_period': number;
    /**
     * 
     * @type {number}
     * @memberof VoiceSharingResponseModel
     */
    'disable_at_unix': number;
    /**
     * 
     * @type {boolean}
     * @memberof VoiceSharingResponseModel
     */
    'voice_mixing_allowed': boolean;
    /**
     * 
     * @type {string}
     * @memberof VoiceSharingResponseModel
     */
    'instagram_username': string;
    /**
     * 
     * @type {string}
     * @memberof VoiceSharingResponseModel
     */
    'twitter_username': string;
    /**
     * 
     * @type {string}
     * @memberof VoiceSharingResponseModel
     */
    'youtube_username': string;
    /**
     * 
     * @type {string}
     * @memberof VoiceSharingResponseModel
     */
    'tiktok_username': string;
    /**
     * 
     * @type {boolean}
     * @memberof VoiceSharingResponseModel
     */
    'featured': boolean;
    /**
     * 
     * @type {string}
     * @memberof VoiceSharingResponseModel
     */
    'ban_reason': string;
    /**
     * 
     * @type {number}
     * @memberof VoiceSharingResponseModel
     */
    'liked_by_count': number;
    /**
     * 
     * @type {number}
     * @memberof VoiceSharingResponseModel
     */
    'cloned_by_count': number;
    /**
     * 
     * @type {string}
     * @memberof VoiceSharingResponseModel
     */
    'name': string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof VoiceSharingResponseModel
     */
    'labels': { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof VoiceSharingResponseModel
     */
    'review_status': VoiceSharingResponseModelReviewStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof VoiceSharingResponseModel
     */
    'review_message': string;
    /**
     * 
     * @type {boolean}
     * @memberof VoiceSharingResponseModel
     */
    'enabled_in_library': boolean;
}

type VoiceSharingResponseModelStatusEnum = 'enabled' | 'disabled' | 'copied' | 'copied_disabled'
type VoiceSharingResponseModelReviewStatusEnum = 'not_requested' | 'pending' | 'declined' | 'allowed' | 'allowed_with_changes'


